"""create contacts

Revision ID: 0b77bf3a961c
Revises: 562cc88b0e66
Create Date: 2026-08-26 10:47:30.493194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b77bf3a961c'
down_revision: Union[str, Sequence[str], None] = '562cc88b0e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.Enum('lead', 'customer', 'blocked', name='contact_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'lead'"), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'external_id', name='uq_contacts_workspace_id_external_id'),
    sa.UniqueConstraint('workspace_id', 'phone_number', name='uq_contacts_workspace_id_phone_number')
    )
    op.create_index('ix_contacts_workspace_id_created_at', 'contacts', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_workspace_id_created_at', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
