"""create support grants

Revision ID: 0d9f60f4e1d9
Revises: 8a9d49afae65
Create Date: 2026-09-02 12:57:38.174721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d9f60f4e1d9'
down_revision: Union[str, Sequence[str], None] = '8a9d49afae65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

AUDIT_EVENTS = (
    'workspace.created',
    'workspace.updated',
    'workspace.closed',
    'member.invited',
    'member.joined',
    'member.role_changed',
    'member.removed',
    'whatsapp.connected',
    'whatsapp.disconnected',
    'knowledge.document_uploaded',
    'knowledge.document_deleted',
    'conversation.assigned',
    'conversation.closed',
    'conversation.ai_disabled',
    'subscription.changed',
    'api_key.created',
    'api_key.revoked',
    'support.access_granted',
    'support.access_ended',
)

ADMIN_ACTIONS = (
    'console.opened',
    'staff.listed',
    'staff.granted',
    'staff.role_changed',
    'staff.revoked',
    'audit.read',
    'workspaces.searched',
    'workspace.read',
    'workspace.members_read',
    'workspace.subscription_read',
    'workspace.usage_read',
    'workspace.integrations_read',
    'workspace.audit_read',
    'users.searched',
    'user.read',
    'support_access.granted',
    'support_access.revoked',
    'support_access.listed',
    'workspace.conversations_read',
    'workspace.messages_read',
)

# What each vocabulary gains here, kept apart so the downgrade can name
# exactly what it has to remove.
NEW_AUDIT_EVENTS = ('support.access_granted', 'support.access_ended')
NEW_ADMIN_ACTIONS = (
    'support_access.granted',
    'support_access.revoked',
    'support_access.listed',
    'workspace.conversations_read',
    'workspace.messages_read',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_grants_staff_user_id'), 'support_grants', ['staff_user_id'], unique=False)
    op.create_index('ix_support_grants_workspace_id_created_at', 'support_grants', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_support_grants_workspace_id_staff_user_id', 'support_grants', ['workspace_id', 'staff_user_id'], unique=False)
    # ### end Alembic commands ###

    # Both logs learn about support access in the same migration as the
    # table, because they describe the same act from two sides and a
    # deployment that had one without the other could grant access it
    # could not record.
    #
    # The tenant's log gains two events, which are the only entries in it
    # that are not about the business's own people. That is deliberate:
    # principle four of the admin plan is that a customer can always see
    # that staff touched their workspace.
    op.drop_constraint('audit_event', 'audit_logs', type_='check')
    op.create_check_constraint(
        'audit_event',
        'audit_logs',
        sa.column('event').in_(AUDIT_EVENTS),
    )

    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(ADMIN_ACTIONS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrowing a vocabulary would refuse rows that already exist, so what
    # this migration admitted goes first. Both deletions destroy evidence:
    # the tenant's record that staff were in their workspace, and the
    # platform's record of what was read. Take a copy before running it.
    _forget('audit_logs', 'event', NEW_AUDIT_EVENTS)
    op.drop_constraint('audit_event', 'audit_logs', type_='check')
    op.create_check_constraint(
        'audit_event',
        'audit_logs',
        sa.column('event').in_(_without(AUDIT_EVENTS, NEW_AUDIT_EVENTS)),
    )

    _forget('admin_audit_logs', 'action', NEW_ADMIN_ACTIONS)
    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(_without(ADMIN_ACTIONS, NEW_ADMIN_ACTIONS)),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_support_grants_workspace_id_staff_user_id', table_name='support_grants')
    op.drop_index('ix_support_grants_workspace_id_created_at', table_name='support_grants')
    op.drop_index(op.f('ix_support_grants_staff_user_id'), table_name='support_grants')
    op.drop_table('support_grants')
    # ### end Alembic commands ###


def _forget(table: str, column: str, values: Sequence[str]) -> None:
    """Delete the rows a narrowed constraint would refuse."""
    listed = ", ".join(repr(value) for value in values)

    op.execute(f"DELETE FROM {table} WHERE {column} IN ({listed})")


def _without(vocabulary: Sequence[str], removed: Sequence[str]) -> list[str]:
    return [value for value in vocabulary if value not in removed]
