"""grant plans the provider does not know about

Revision ID: 23a171f664e9
Revises: d209996b5e5c
Create Date: 2026-09-02 13:25:41.110698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a171f664e9'
down_revision: Union[str, Sequence[str], None] = 'd209996b5e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ADMIN_ACTIONS = (
    'console.opened',
    'staff.listed',
    'staff.granted',
    'staff.role_changed',
    'staff.revoked',
    'audit.read',
    'workspaces.searched',
    'workspace.read',
    'workspace.members_read',
    'workspace.subscription_read',
    'workspace.usage_read',
    'workspace.integrations_read',
    'workspace.audit_read',
    'users.searched',
    'user.read',
    'support_access.granted',
    'support_access.revoked',
    'support_access.listed',
    'workspace.conversations_read',
    'workspace.messages_read',
    'workspace.suspended',
    'workspace.unsuspended',
    'workspace.cancelled',
    'workspace.restored',
    'workspace.erase_after_changed',
    'workspace.erased',
    'workspace.erase_refused',
    'user.deactivated',
    'user.activated',
    'user.sessions_revoked',
    'user.email_verified',
    'billing.subscriptions_searched',
    'billing.plan_override_granted',
    'billing.plan_override_removed',
    'billing.events_read',
    'billing.event_replayed',
)

NEW_ADMIN_ACTIONS = (
    'billing.subscriptions_searched',
    'billing.plan_override_granted',
    'billing.plan_override_removed',
    'billing.events_read',
    'billing.event_replayed',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('starter', 'growth', 'business', name='plan_override_tier', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', name='uq_plan_overrides_workspace_id')
    )
    # Existing rows get an empty payload rather than a backfill, and
    # there is nothing to backfill from: the deliveries this application
    # handled before today were acted on and not kept. Replaying one of
    # them is not possible and the console will say so, which is honest
    # -- inventing a payload from the subscription's current state would
    # replay something the provider never sent.
    op.add_column('billing_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###

    # Nothing here reads `subscriptions.plan` to decide what a workspace
    # may do any more -- one function does, and it consults this table
    # first. See SubscriptionService.plan_for and the SQL twin of it in
    # app/repositories/admin_console_repository.py.
    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(ADMIN_ACTIONS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Every granted plan goes with the table, so a workspace comped by
    # agreement drops to whatever the provider last said about it --
    # which for a customer invoiced offline is the free plan. Read the
    # overrides out before running this, or somebody loses features they
    # were promised.
    listed = ", ".join(repr(action) for action in NEW_ADMIN_ACTIONS)
    op.execute(f"DELETE FROM admin_audit_logs WHERE action IN ({listed})")
    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(
            [a for a in ADMIN_ACTIONS if a not in NEW_ADMIN_ACTIONS]
        ),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_events', 'payload')
    op.drop_table('plan_overrides')
    # ### end Alembic commands ###
