"""add inbox unread state

Revision ID: 5c75fa33a694
Revises: fb92cf688b6e
Create Date: 2026-08-27 13:32:36.955930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c75fa33a694'
down_revision: Union[str, Sequence[str], None] = 'fb92cf688b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('conversations', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_read_at')
    op.drop_column('conversations', 'unread_count')
    # ### end Alembic commands ###
