"""order the inbox index the way the inbox sorts

Revision ID: 5e88ec66f89f
Revises: 5c75fa33a694
Create Date: 2026-08-27 14:03:38.284707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e88ec66f89f'
down_revision: Union[str, Sequence[str], None] = '5c75fa33a694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The old index ordered by (workspace_id, last_message_at DESC), which
    # is not the order the inbox asks for: the sort is DESC NULLS LAST and
    # breaks ties on created_at and id. An index that orders differently
    # cannot be used to order by at all, so PostgreSQL was joining a
    # workspace's whole history to its contacts and last messages, sorting
    # all of it, and returning thirty rows -- half a second at twenty
    # thousand conversations, against one millisecond after this.
    op.drop_index(op.f('ix_conversations_workspace_id_last_message_at'), table_name='conversations')
    op.create_index('ix_conversations_inbox_order', 'conversations', ['workspace_id', sa.literal_column('last_message_at DESC NULLS LAST'), sa.literal_column('created_at DESC'), 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_inbox_order', table_name='conversations')
    op.create_index(op.f('ix_conversations_workspace_id_last_message_at'), 'conversations', ['workspace_id', sa.literal_column('last_message_at DESC')], unique=False)
    # ### end Alembic commands ###
