"""add human handoff and its audit trail

Revision ID: 75ed83dd4129
Revises: ab47bbc317cd
Create Date: 2026-08-27 15:19:19.094468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ed83dd4129'
down_revision: Union[str, Sequence[str], None] = 'ab47bbc317cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('ai_handoff', 'human_takeover', 'ai_released', name='conversation_event_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id', 'conversation_id'], ['conversations.workspace_id', 'conversations.id'], name='fk_conversation_events_conversation_in_same_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_index('ix_conversation_events_conversation_id_created_at', 'conversation_events', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_conversation_events_workspace_id_created_at', 'conversation_events', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('conversations', sa.Column('handoff_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('handoff_reason', sa.String(length=200), nullable=True))
    op.add_column('conversations', sa.Column('handoff_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_conversations_handoff_by_user_id_users', 'conversations', 'users', ['handoff_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_handoff_by_user_id_users', 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'handoff_by_user_id')
    op.drop_column('conversations', 'handoff_reason')
    op.drop_column('conversations', 'handoff_at')
    op.drop_index('ix_conversation_events_workspace_id_created_at', table_name='conversation_events')
    op.drop_index('ix_conversation_events_conversation_id_created_at', table_name='conversation_events')
    op.drop_table('conversation_events')
    # ### end Alembic commands ###
