"""record refused deliveries and let a job be cancelled

Revision ID: 8edd5fd4705d
Revises: 23a171f664e9
Create Date: 2026-09-02 13:40:00.776923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edd5fd4705d'
down_revision: Union[str, Sequence[str], None] = '23a171f664e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ADMIN_ACTIONS = (
    'console.opened',
    'staff.listed',
    'staff.granted',
    'staff.role_changed',
    'staff.revoked',
    'audit.read',
    'workspaces.searched',
    'workspace.read',
    'workspace.members_read',
    'workspace.subscription_read',
    'workspace.usage_read',
    'workspace.integrations_read',
    'workspace.audit_read',
    'users.searched',
    'user.read',
    'support_access.granted',
    'support_access.revoked',
    'support_access.listed',
    'workspace.conversations_read',
    'workspace.messages_read',
    'workspace.suspended',
    'workspace.unsuspended',
    'workspace.cancelled',
    'workspace.restored',
    'workspace.erase_after_changed',
    'workspace.erased',
    'workspace.erase_refused',
    'user.deactivated',
    'user.activated',
    'user.sessions_revoked',
    'user.email_verified',
    'billing.subscriptions_searched',
    'billing.plan_override_granted',
    'billing.plan_override_removed',
    'billing.events_read',
    'billing.event_replayed',
    'ops.jobs_searched',
    'ops.job_read',
    'ops.job_retried',
    'ops.job_cancelled',
    'ops.webhook_failures_read',
    'ops.whatsapp_health_read',
    'ops.health_read',
)

JOB_STATUSES = (
    'pending',
    'running',
    'succeeded',
    'failed',
    'cancelled',
)

NEW_ADMIN_ACTIONS = (
    'ops.jobs_searched',
    'ops.job_read',
    'ops.job_retried',
    'ops.job_cancelled',
    'ops.webhook_failures_read',
    'ops.whatsapp_health_read',
    'ops.health_read',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_failures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Enum('bad_signature', 'unknown_subject', 'malformed', name='webhook_refusal', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_failures_received_at', 'webhook_failures', ['provider', 'received_at'], unique=False)
    # ### end Alembic commands ###

    # A job can now be stopped by a person as well as by the runner
    # giving up, which the status constraint has to admit.
    op.drop_constraint('job_status', 'jobs', type_='check')
    op.create_check_constraint(
        'job_status',
        'jobs',
        sa.column('status').in_(JOB_STATUSES),
    )

    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(ADMIN_ACTIONS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # A cancelled job becomes a failed one rather than being deleted.
    # Losing the row would lose the record that somebody decided not to
    # do the work, and `failed` is the nearest thing the narrower
    # vocabulary can say about it.
    op.execute("UPDATE jobs SET status = 'failed' WHERE status = 'cancelled'")
    op.drop_constraint('job_status', 'jobs', type_='check')
    op.create_check_constraint(
        'job_status',
        'jobs',
        sa.column('status').in_([s for s in JOB_STATUSES if s != 'cancelled']),
    )

    listed = ", ".join(repr(action) for action in NEW_ADMIN_ACTIONS)
    op.execute(f"DELETE FROM admin_audit_logs WHERE action IN ({listed})")
    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(
            [a for a in ADMIN_ACTIONS if a not in NEW_ADMIN_ACTIONS]
        ),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_failures_received_at', table_name='webhook_failures')
    op.drop_table('webhook_failures')
    # ### end Alembic commands ###
