"""require a second person for the two most serious acts

Revision ID: 9709660d9f0d
Revises: 3b28a09199d9
Create Date: 2026-09-02 13:55:57.121099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9709660d9f0d'
down_revision: Union[str, Sequence[str], None] = '3b28a09199d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ADMIN_ACTIONS = (
    'console.opened',
    'staff.listed',
    'staff.granted',
    'staff.role_changed',
    'staff.revoked',
    'audit.read',
    'workspaces.searched',
    'workspace.read',
    'workspace.members_read',
    'workspace.subscription_read',
    'workspace.usage_read',
    'workspace.integrations_read',
    'workspace.audit_read',
    'users.searched',
    'user.read',
    'support_access.granted',
    'support_access.revoked',
    'support_access.listed',
    'workspace.conversations_read',
    'workspace.messages_read',
    'workspace.suspended',
    'workspace.unsuspended',
    'workspace.cancelled',
    'workspace.restored',
    'workspace.erase_after_changed',
    'workspace.erased',
    'workspace.erase_refused',
    'user.deactivated',
    'user.activated',
    'user.sessions_revoked',
    'user.email_verified',
    'billing.subscriptions_searched',
    'billing.plan_override_granted',
    'billing.plan_override_removed',
    'billing.events_read',
    'billing.event_replayed',
    'ops.jobs_searched',
    'ops.job_read',
    'ops.job_retried',
    'ops.job_cancelled',
    'ops.webhook_failures_read',
    'ops.whatsapp_health_read',
    'ops.health_read',
    'analytics.read',
    'approval.requested',
    'approval.granted',
    'approval.spent',
    'approval.listed',
    'alerts.read',
)

JOB_KINDS = (
    'deliver_message',
    'sweep_automations',
    'run_due_automations',
    'sweep_erasures',
    'sweep_support_grants',
    'erase_workspace',
)

NEW_ADMIN_ACTIONS = (
    'approval.requested',
    'approval.granted',
    'approval.spent',
    'approval.listed',
    'alerts.read',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('erase_workspace', 'grant_staff_owner', name='approvable_action', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_approvals_action_subject', 'admin_approvals', ['action', 'subject'], unique=False)
    # ### end Alembic commands ###

    # The sweep that closes lapsed support grants, and the five actions
    # the approval control records. Both in the same migration as the
    # table, because a deployment with the table and not the vocabulary
    # could raise an approval it was unable to record.
    op.drop_constraint('job_kind', 'jobs', type_='check')
    op.create_check_constraint(
        'job_kind',
        'jobs',
        sa.column('kind').in_(JOB_KINDS),
    )

    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(ADMIN_ACTIONS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Reversing this removes the requirement for a second person on an
    # erasure and on granting owner. The approvals already given go with
    # the table, and the record of who agreed to what goes with the log
    # entries below. Neither is recoverable. Take a copy.
    op.execute("DELETE FROM jobs WHERE kind = 'sweep_support_grants'")
    op.drop_constraint('job_kind', 'jobs', type_='check')
    op.create_check_constraint(
        'job_kind',
        'jobs',
        sa.column('kind').in_(
            [k for k in JOB_KINDS if k != 'sweep_support_grants']
        ),
    )

    listed = ", ".join(repr(action) for action in NEW_ADMIN_ACTIONS)
    op.execute(f"DELETE FROM admin_audit_logs WHERE action IN ({listed})")
    op.drop_constraint('admin_action', 'admin_audit_logs', type_='check')
    op.create_check_constraint(
        'admin_action',
        'admin_audit_logs',
        sa.column('action').in_(
            [a for a in ADMIN_ACTIONS if a not in NEW_ADMIN_ACTIONS]
        ),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_approvals_action_subject', table_name='admin_approvals')
    op.drop_table('admin_approvals')
    # ### end Alembic commands ###
