"""create knowledge base and ai response logs

Revision ID: ab47bbc317cd
Revises: 5e88ec66f89f
Create Date: 2026-08-27 14:09:37.768707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab47bbc317cd'
down_revision: Union[str, Sequence[str], None] = '5e88ec66f89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.Enum('text', 'file', 'manual_faq', name='knowledge_source_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='knowledge_source_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_sources_workspace_id_id')
    )
    op.create_index('ix_knowledge_sources_workspace_id_created_at', 'knowledge_sources', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='knowledge_document_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'knowledge_source_id'], ['knowledge_sources.workspace_id', 'knowledge_sources.id'], name='fk_knowledge_documents_source_in_same_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'content_hash', name='uq_knowledge_documents_workspace_id_content_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_knowledge_documents_workspace_id_id')
    )
    op.create_index('ix_knowledge_documents_workspace_id_created_at', 'knowledge_documents', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'document_id'], ['knowledge_documents.workspace_id', 'knowledge_documents.id'], name='fk_knowledge_chunks_document_in_same_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_knowledge_chunks_document_id_chunk_index')
    )
    op.create_index('ix_knowledge_chunks_workspace_id', 'knowledge_chunks', ['workspace_id'], unique=False)
    op.create_table('ai_response_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('sent_message_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('answered', 'suggested', 'handoff', 'blocked', 'failed', name='ai_decision', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('retrieval_query', sa.Text(), nullable=True),
    sa.Column('retrieved_chunk_ids', postgresql.ARRAY(sa.Uuid()), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sent_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id', 'conversation_id'], ['conversations.workspace_id', 'conversations.id'], name='fk_ai_response_logs_conversation_in_same_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_index('ix_ai_response_logs_conversation_id', 'ai_response_logs', ['conversation_id'], unique=False)
    op.create_index('ix_ai_response_logs_workspace_id_created_at', 'ai_response_logs', ['workspace_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_response_logs_workspace_id_created_at', table_name='ai_response_logs')
    op.drop_index('ix_ai_response_logs_conversation_id', table_name='ai_response_logs')
    op.drop_table('ai_response_logs')
    op.drop_index('ix_knowledge_chunks_workspace_id', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_documents_workspace_id_created_at', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_knowledge_sources_workspace_id_created_at', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
