"""schedule erasure for closed workspaces

Revision ID: b7e51ca9034d
Revises: a92e7c40db85
Create Date: 2026-09-01 17:12:55.019283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e51ca9034d'
down_revision: Union[str, Sequence[str], None] = 'a92e7c40db85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

JOB_KINDS = (
    'deliver_message',
    'sweep_automations',
    'run_due_automations',
    'erase_workspace',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'workspaces',
        sa.Column('erase_after', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###

    # Workspaces closed before this migration keep their data and get no
    # date. Backfilling one would destroy records on a schedule nobody was
    # ever told about, which is the opposite of what a retention policy is
    # for -- the clock starts when somebody is told it has.

    op.drop_constraint('job_kind', 'jobs', type_='check')
    op.create_check_constraint(
        'job_kind',
        'jobs',
        sa.column('kind').in_(JOB_KINDS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrowing the vocabulary would refuse rows that already exist, so any
    # queued erasure goes first. Losing it is the safe direction: the
    # workspace keeps its data and its date, and the next sweep on an
    # upgraded deployment queues the job again.
    op.execute("DELETE FROM jobs WHERE kind = 'erase_workspace'")
    op.drop_constraint('job_kind', 'jobs', type_='check')
    op.create_check_constraint(
        'job_kind',
        'jobs',
        sa.column('kind').in_(JOB_KINDS[:-1]),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'erase_after')
    # ### end Alembic commands ###
