"""create automations and runs

Revision ID: b8e4d2f60c19
Revises: a3f18c7d5b02
Create Date: 2026-08-31 09:12:44.180233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b8e4d2f60c19'
down_revision: Union[str, Sequence[str], None] = 'a3f18c7d5b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('order_confirmation', 'human_handoff', 'unanswered_lead_followup', name='automation_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trigger_type', sa.Enum('message_received', 'order_created', 'schedule', name='automation_trigger', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('enabled', 'disabled', name='automation_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'enabled'"), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_automations_workspace_id_id'),
    sa.UniqueConstraint('workspace_id', 'kind', name='uq_automations_workspace_id_kind')
    )
    op.create_index('ix_automations_workspace_id_trigger_type', 'automations', ['workspace_id', 'trigger_type', 'status'], unique=False)
    op.create_table('automation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('automation_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('running', 'succeeded', 'failed', 'skipped', name='automation_run_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'automation_id'], ['automations.workspace_id', 'automations.id'], name='fk_automation_runs_automation_in_same_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('automation_id', 'dedupe_key', name='uq_automation_runs_automation_id_dedupe_key')
    )
    op.create_index('ix_automation_runs_automation_id_started_at', 'automation_runs', ['automation_id', sa.text('started_at DESC')], unique=False)
    op.create_index('ix_automation_runs_workspace_id_started_at', 'automation_runs', ['workspace_id', sa.text('started_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_automation_runs_workspace_id_started_at', table_name='automation_runs')
    op.drop_index('ix_automation_runs_automation_id_started_at', table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_index('ix_automations_workspace_id_trigger_type', table_name='automations')
    op.drop_table('automations')
    # ### end Alembic commands ###
