"""create audit logs

Revision ID: c81f56d3a704
Revises: e7b1c4d92a35
Create Date: 2026-09-01 12:04:18.771942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c81f56d3a704'
down_revision: Union[str, Sequence[str], None] = 'e7b1c4d92a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

AUDIT_EVENTS = (
    'workspace.created',
    'workspace.updated',
    'member.invited',
    'member.joined',
    'member.role_changed',
    'member.removed',
    'whatsapp.connected',
    'whatsapp.disconnected',
    'knowledge.document_uploaded',
    'knowledge.document_deleted',
    'conversation.assigned',
    'conversation.closed',
    'conversation.ai_disabled',
    'subscription.changed',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.Enum(*AUDIT_EVENTS, name='audit_event', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_index('ix_audit_logs_workspace_id_actor_user_id', 'audit_logs', ['workspace_id', 'actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_workspace_id_sequence', 'audit_logs', ['workspace_id', sa.text('sequence DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_workspace_id_sequence', table_name='audit_logs')
    op.drop_index('ix_audit_logs_workspace_id_actor_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
