"""create subscriptions and billing events

Revision ID: d4a29b1f7c85
Revises: c9d51ea7b346
Create Date: 2026-08-31 13:41:52.663104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a29b1f7c85'
down_revision: Union[str, Sequence[str], None] = 'c9d51ea7b346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

NOTIFICATION_KINDS = (
    'conversation_assigned',
    'handoff_requested',
    'knowledge_ingestion_failed',
    'message_delivery_failed',
    'billing_payment_failed',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('stripe', name='billing_event_provider', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_billing_events_provider_provider_event_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('stripe', name='billing_provider', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.Enum('starter', 'growth', 'business', name='plan_tier', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'unpaid', 'canceled', 'incomplete', name='subscription_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_subscription_id', name='uq_subscriptions_provider_subscription_id'),
    sa.UniqueConstraint('workspace_id', name='uq_subscriptions_workspace_id')
    )
    # ### end Alembic commands ###

    # Billing gives people one more thing to be told about, and the kind
    # column is a CHECK constraint rather than a native ENUM -- which is
    # exactly so that widening the vocabulary is an ordinary drop and
    # recreate. See app/db/types.py, which chose that trade for moments
    # like this one.
    op.drop_constraint('notification_kind', 'notifications', type_='check')
    op.create_check_constraint(
        'notification_kind',
        'notifications',
        sa.column('kind').in_(NOTIFICATION_KINDS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrowing it again would refuse rows that already exist, so the
    # billing notifications go first. Nothing is lost that anybody needs:
    # a payment that failed has a subscription row saying so.
    op.execute("DELETE FROM notifications WHERE kind = 'billing_payment_failed'")
    op.drop_constraint('notification_kind', 'notifications', type_='check')
    op.create_check_constraint(
        'notification_kind',
        'notifications',
        sa.column('kind').in_(NOTIFICATION_KINDS[:-1]),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
