"""create staff members and the admin audit log

Revision ID: d8239847fa74
Revises: b7e51ca9034d
Create Date: 2026-09-02 11:30:14.796214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8239847fa74'
down_revision: Union[str, Sequence[str], None] = 'b7e51ca9034d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # No row is seeded here. A migration that granted the platform to an
    # address would put a privileged account in version control, the same
    # in every deployment and impossible to review after the fact. The
    # first owner is granted from the command line instead -- see
    # app/staff_cli.py -- which is one command, run once, by whoever
    # actually operates the deployment.

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('support', 'admin', 'owner', name='staff_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # Two things below are load-bearing and neither is a slip.
    #
    # `workspace_id` is nullable, because granting a colleague access is
    # about no workspace at all. And it is ON DELETE SET NULL where every
    # other tenant-owned table cascades, because the row this table exists
    # to keep -- somebody read this workspace shortly before it was erased
    # -- is precisely the row a cascade would delete at the moment it
    # started to matter. `workspace_slug` is copied alongside so the
    # surviving row can still name its subject.
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.Enum('console.opened', 'staff.listed', 'staff.granted', 'staff.role_changed', 'staff.revoked', 'audit.read', name='admin_action', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('workspace_slug', sa.String(length=63), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_index('ix_admin_audit_logs_actor_user_id_sequence', 'admin_audit_logs', ['actor_user_id', sa.literal_column('sequence DESC')], unique=False)
    op.create_index('ix_admin_audit_logs_sequence', 'admin_audit_logs', [sa.literal_column('sequence DESC')], unique=False)
    op.create_index('ix_admin_audit_logs_workspace_id_sequence', 'admin_audit_logs', ['workspace_id', sa.literal_column('sequence DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Dropping admin_audit_logs destroys the record of what staff did,
    # which nothing else in this schema keeps a copy of. That is what
    # reversing this migration means, and it is worth saying out loud
    # before somebody runs it to get past a failed deployment.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_audit_logs_workspace_id_sequence', table_name='admin_audit_logs')
    op.drop_index('ix_admin_audit_logs_sequence', table_name='admin_audit_logs')
    op.drop_index('ix_admin_audit_logs_actor_user_id_sequence', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_table('staff_members')
    # ### end Alembic commands ###
