"""create products, variants and orders

Revision ID: e2b6c9d4517f
Revises: c4a71e35d6b8
Create Date: 2026-08-27 18:58:22.117094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e2b6c9d4517f'
down_revision: Union[str, Sequence[str], None] = 'c4a71e35d6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'draft', 'archived', name='product_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'external_id', name='uq_products_workspace_id_external_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_products_workspace_id_id')
    )
    op.create_index('ix_products_workspace_id_created_at', 'products', ['workspace_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_products_workspace_id_name', 'products', ['workspace_id', 'name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('order_number', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'refunded', name='order_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_address', sa.Text(), nullable=True),
    sa.Column('tracking_number', sa.String(length=128), nullable=True),
    sa.Column('tracking_url', sa.String(length=500), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'contact_id'], ['contacts.workspace_id', 'contacts.id'], name='fk_orders_contact_in_same_workspace', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'external_id', name='uq_orders_workspace_id_external_id')
    )
    op.create_index('ix_orders_workspace_id_contact_id', 'orders', ['workspace_id', 'contact_id', sa.text('placed_at DESC NULLS LAST')], unique=False)
    op.create_index('ix_orders_workspace_id_placed_at', 'orders', ['workspace_id', sa.text('placed_at DESC NULLS LAST'), sa.text('created_at DESC')], unique=False)
    op.create_table('product_variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'product_id'], ['products.workspace_id', 'products.id'], name='fk_product_variants_workspace_id_product_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'external_id', name='uq_product_variants_workspace_id_external_id'),
    sa.UniqueConstraint('workspace_id', 'sku', name='uq_product_variants_workspace_id_sku')
    )
    op.create_index('ix_product_variants_workspace_id_product_id', 'product_variants', ['workspace_id', 'product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_variants_workspace_id_product_id', table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_orders_workspace_id_placed_at', table_name='orders')
    op.drop_index('ix_orders_workspace_id_contact_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_products_workspace_id_name', table_name='products')
    op.drop_index('ix_products_workspace_id_created_at', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
