"""create usage records

Revision ID: e7b1c4d92a35
Revises: d4a29b1f7c85
Create Date: 2026-09-01 09:12:44.108233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b1c4d92a35'
down_revision: Union[str, Sequence[str], None] = 'd4a29b1f7c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.Enum('ai_responses', 'ai_tokens', 'whatsapp_messages', 'active_contacts', 'team_members', 'whatsapp_numbers', 'knowledge_documents', 'knowledge_tokens', name='usage_metric', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'metric', 'source_id', name='uq_usage_records_workspace_id_metric_source_id')
    )
    op.create_index('ix_usage_records_workspace_id_metric_period_start', 'usage_records', ['workspace_id', 'metric', 'period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_records_workspace_id_metric_period_start', table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
