"""create api keys

Revision ID: f4d80b2ce619
Revises: c81f56d3a704
Create Date: 2026-09-01 15:22:07.404918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d80b2ce619'
down_revision: Union[str, Sequence[str], None] = 'c81f56d3a704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

AUDIT_EVENTS = (
    'workspace.created',
    'workspace.updated',
    'member.invited',
    'member.joined',
    'member.role_changed',
    'member.removed',
    'whatsapp.connected',
    'whatsapp.disconnected',
    'knowledge.document_uploaded',
    'knowledge.document_deleted',
    'conversation.assigned',
    'conversation.closed',
    'conversation.ai_disabled',
    'subscription.changed',
    'api_key.created',
    'api_key.revoked',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash', name='uq_api_keys_key_hash')
    )
    op.create_index('ix_api_keys_workspace_id_created_at', 'api_keys', ['workspace_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    # Issuing a key is two more things a business may later have to
    # account for. The audit vocabulary is a CHECK constraint rather than
    # a native ENUM exactly so that widening it is an ordinary drop and
    # recreate. See app/db/types.py, which chose that trade for this.
    op.drop_constraint('audit_event', 'audit_logs', type_='check')
    op.create_check_constraint(
        'audit_event',
        'audit_logs',
        sa.column('event').in_(AUDIT_EVENTS),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrowing it again would refuse rows that already exist, so the key
    # entries go first. Nothing is lost that anybody needs: the table
    # being dropped below is the record of which keys there were.
    op.execute("DELETE FROM audit_logs WHERE event LIKE 'api_key.%'")
    op.drop_constraint('audit_event', 'audit_logs', type_='check')
    op.create_check_constraint(
        'audit_event',
        'audit_logs',
        sa.column('event').in_(AUDIT_EVENTS[:-2]),
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_keys_workspace_id_created_at', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
