"""create ecommerce accounts

Revision ID: f7c30a81be24
Revises: e2b6c9d4517f
Create Date: 2026-08-27 19:41:08.552310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c30a81be24'
down_revision: Union[str, Sequence[str], None] = 'e2b6c9d4517f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('shopify', name='ecommerce_provider', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('shop_domain', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', name='ecommerce_account_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_domain', name='uq_ecommerce_accounts_shop_domain'),
    sa.UniqueConstraint('workspace_id', name='uq_ecommerce_accounts_workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecommerce_accounts')
    # ### end Alembic commands ###
