"""create whatsapp accounts

Revision ID: fb92cf688b6e
Revises: fd3fc36a984b
Create Date: 2026-08-26 16:37:04.070866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb92cf688b6e'
down_revision: Union[str, Sequence[str], None] = 'fd3fc36a984b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('meta_cloud', name='messaging_provider', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('external_phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('external_business_account_id', sa.String(length=64), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', name='whatsapp_account_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_phone_number_id', name='uq_whatsapp_accounts_external_phone_number_id'),
    sa.UniqueConstraint('workspace_id', name='uq_whatsapp_accounts_workspace_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
