"""create conversations and messages

Revision ID: fd3fc36a984b
Revises: 0b77bf3a961c
Create Date: 2026-08-26 13:27:33.079310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3fc36a984b'
down_revision: Union[str, Sequence[str], None] = '0b77bf3a961c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-moved to the front. Autogenerate put this last, after the
    # conversations table whose composite foreign key points at it, and
    # PostgreSQL will not create a foreign key whose target has no
    # matching unique constraint yet.
    op.create_unique_constraint('uq_contacts_workspace_id_id', 'contacts', ['workspace_id', 'id'])
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', name='conversation_channel', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'whatsapp'"), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'closed', name='conversation_status', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'open'"), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('ai_mode', sa.Enum('disabled', 'suggest_only', 'automatic', name='conversation_ai_mode', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'suggest_only'"), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id', 'contact_id'], ['contacts.workspace_id', 'contacts.id'], name='fk_conversations_contact_in_same_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'id', name='uq_conversations_workspace_id_id')
    )
    op.create_index('ix_conversations_workspace_id_last_message_at', 'conversations', ['workspace_id', sa.literal_column('last_message_at DESC')], unique=False)
    op.create_index('uq_conversations_one_open_per_contact', 'conversations', ['workspace_id', 'contact_id', 'channel'], unique=True, postgresql_where=sa.text("status <> 'closed'"))
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_type', sa.Enum('customer', 'agent', 'ai', 'system', name='message_sender_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', name='message_channel', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'whatsapp'"), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.Enum('text', name='message_content_type', native_enum=False, create_constraint=True, length=32), server_default=sa.text("'text'"), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', 'received', name='message_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'conversation_id'], ['conversations.workspace_id', 'conversations.id'], name='fk_messages_conversation_in_same_workspace', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence'),
    sa.UniqueConstraint('workspace_id', 'external_message_id', name='uq_messages_workspace_id_external_message_id')
    )
    op.create_index('ix_messages_conversation_id_created_at', 'messages', ['conversation_id', 'created_at', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_messages_conversation_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_conversations_one_open_per_contact', table_name='conversations', postgresql_where=sa.text("status <> 'closed'"))
    op.drop_index('ix_conversations_workspace_id_last_message_at', table_name='conversations')
    op.drop_table('conversations')
    # After the tables that reference it, for the same reason.
    op.drop_constraint('uq_contacts_workspace_id_id', 'contacts', type_='unique')
    # ### end Alembic commands ###
